project:
  type: website
  output-dir: docs

website:
  title: "[datadavidz]"
  site-url: https://datadavidz.github.io
  description: "Personal blog"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/datadavidz
      - icon: twitter
        href: https://twitter.com/datadavidz
format:
  html:
    theme: cosmo
    css: styles.css



