# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_s3(bucket = "pins-test-zoller", region = structure("us-east-2", tags = list(type = "scalar")))
v <- vetiver_pin_read(b, "concrete-xgb", version = "20221019T191525Z-b1278")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
